version: '2'
services:
  mysql_1:
    image: mysql:5.7
    container_name: 'mysql_1'
    volumes:
      - './etc/mysql_1/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
    ports:
      - "3307:3306" 
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  mysql_2:
    image: mysql:5.7
    container_name: 'mysql_2'
    volumes:
      - './etc/mysql_2/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
    ports:
      - "3308:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
